name: Create Release

on:
  push:
    branches:
      - main

jobs:
  check_release:
    runs-on: ubuntu-latest
    outputs:
      release: ${{ steps.extract_release.outputs.RELEASE }}
    
    steps:
    - uses: actions/checkout@v2

    - name: Extract release number from commit message
      id: extract_release
      run: |
        COMMIT_MSG=$(git log --format=%B -n 1 ${{ github.sha }})
        if [[ $COMMIT_MSG == release* ]]; then
          RELEASE=$(echo ${COMMIT_MSG#release} | xargs | cut -d" " -f1)
          echo "::set-output name=RELEASE::$RELEASE"
        fi  

  prepare_release:
    needs: check_release
    if: needs.check_release.outputs.release != ''
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Update release version in a file
      run: |
        sed -i 's/\("version":\s*"\)[^"]*"/\1'"${{ needs.check_release.outputs.release }}"'"/' system.json
        sed -i 's|\("/download/v\)[^"]*|\1'"${{ needs.check_release.outputs.release }}"'|g' system.json
        sed -i 's|\("/foundryvtt/v\)[^"]*|\1'"${{ needs.check_release.outputs.release }}"'|g' system.json
        sed -i 's|\("/foundryvtt/releases/download/v\)[^"]*|\1'"${{ needs.check_release.outputs.release }}"'|g' system.json
      
    - name: Archive code
      run: |
        zip -r hero6efoundryvtt2.zip .

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: hero6efoundryvtt2.zip
        path: hero6efoundryvtt2.zip

    - name: Create and push tag
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git tag ${{ needs.check_release.outputs.release }}
        git push origin ${{ needs.check_release.outputs.release }}

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ needs.check_release.outputs.release }}
        release_name: Release ${{ needs.check_release.outputs.release }}
        draft: false
        prerelease: false

    - name: Upload system zip
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./hero6efoundryvtt2.zip
        asset_name: hero6efoundryvtt2.zip
        asset_content_type: application/zip

    - name: Upload system.json
      id: upload-system-json
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./system.json
        asset_name: system.json
        asset_content_type: application/json